# stage 1
FROM python:3.12-slim AS builder

#  Ваш код здесь #
WORKDIR /app
COPY . .
RUN python -m venv /app/venv
ENV PATH="/app/venv/bin:$PATH"
RUN pip install --no-cache-dir -r requirements.txt

# stage 2
FROM python:3.12-slim
WORKDIR /app
COPY main.py .

COPY --from=builder  /app/venv ./venv
ENV PATH="/app/venv/bin:$PATH"

EXPOSE 5000

# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"] 